### ISSUE TITLE
Error during launch of chunk splitting script (Metashape pro version 1.7)

### ISSUE THREAD

**Issue by Andrea-arch-lab** [agisoft-llc/metashape-scripts#114]
Hi, I tried to run the split cloud process with the script, but it gives me this error:

2024-12-14 16:19:21 Traceback (most recent call last):
2024-12-14 16:19:21   File "D:/03. Tempio di Diana - Roma/Roma - Tempietto di Diana/Script/split_in_chunks_dialog.py", line 157, in <lambda>
2024-12-14 16:19:21     proc_split = lambda: self.splitChunks()
2024-12-14 16:19:21   File "D:/03. Tempio di Diana - Roma/Roma - Tempietto di Diana/Script/split_in_chunks_dialog.py", line 368, in splitChunks
2024-12-14 16:19:21     new_chunk.point_cloud.clear()
2024-12-14 16:19:21 AttributeError: 'Metashape.PointCloud' object has no attribute 'clear'
>>> 

Can anyone help me?

**Comment by PolarNick239** [comment]
Hi, [the latest version](https://github.com/agisoft-llc/metashape-scripts/blob/master/src/split_in_chunks_dialog.py) of split_in_chunks_dialog.py is compatible only with latest stable Metashape release - for now it is 2.1.

If you want to continue use Metashape 1.7 - you can try to use [the script from the 1.7 branch](https://github.com/agisoft-llc/metashape-scripts/blob/1.7/src/split_in_chunks_dialog.py), does it work for you?
