### ISSUE TITLE
Split into Chunks Not Building Dense Cloud

### ISSUE THREAD

**Issue by pdxvr** [agisoft-llc/metashape-scripts#6]
Maybe I'm trying to use it incorrectly but it works great to build the mesh once I have my dense cloud.  Is there a method to build the dense cloud in the chunks using this script?  It just duplicates my chunk once and doesn't build a dense cloud

**Comment by PolarNick239** [comment]
Are there any errors in the log? Can you please attach it?

**Comment by PeterJared** [comment]
pdxvr , I only have tested once to build the dense cloud but it worked. I suppose you have done first the photos alignment before running the script.

**Comment by pdxvr** [comment]
Here's my log.  Yes aligned already.

`2019-04-11 10:54:04 Script started
2019-04-11 10:54:04 DuplicateChunk: items = (keypoints, dense cloud)
2019-04-11 10:54:04 Finished processing in 0.002931 sec (exit code 1)
2019-04-11 10:54:04 Traceback (most recent call last):
2019-04-11 10:54:04   File "/Volumes/SSD/Lab 2 Data/SplitIntoChunks.py", line 110, in <lambda>
2019-04-11 10:54:04     proc_split = lambda : self.splitChunks()
2019-04-11 10:54:04   File "/Volumes/SSD/PCC/Lab 2 Data/SplitIntoChunks.py", line 228, in splitChunks
2019-04-11 10:54:04     new_chunk.buildDenseCloud(quality = PhotoScan.Quality.HighQuality, filter = PhotoScan.FilterMode.AggressiveFiltering, keep_depth = False, reuse_depth = reuse_depth)
2019-04-11 10:54:04 TypeError: 'quality' is an invalid keyword argument for this function
`

**Comment by pdxvr** [comment]
I downloaded the newest script, replaced the Metashape with Photoscan and the version to 1.4 and it works fine.

**Comment by pdxvr** [comment]
This issue is happening again, I didn't change anything, it just stopped working again

**Comment by pdxvr** [comment]
```
2019-06-11 10:05:41 Script started...
2019-06-11 10:05:41 DuplicateChunk: items = ()
2019-06-11 10:05:41 Duplicating chunk...
2019-06-11 10:05:42 Finished processing in 0.662 sec (exit code 1)
2019-06-11 10:05:42 Traceback (most recent call last):
2019-06-11 10:05:42   File "C:/Users/mmm/Desktop/252/Python/ChunksPS2.py", line 152, in <lambda>
2019-06-11 10:05:42     proc_split = lambda: self.splitChunks()
2019-06-11 10:05:42   File "C:/Users/mmm/Desktop/252/Python/ChunksPS2.py", line 290, in splitChunks
2019-06-11 10:05:42     if new_chunk.depth_maps.meta['depth/depth_downscale']:
2019-06-11 10:05:42 AttributeError: 'NoneType' object has no attribute 'meta'
```

**Comment by pdxvr** [comment]
2019-06-11 10:05:41 Script started...
2019-06-11 10:05:41 DuplicateChunk: items = ()
2019-06-11 10:05:41 Duplicating chunk...
2019-06-11 10:05:42 Finished processing in 0.662 sec (exit code 1)
2019-06-11 10:05:42 Traceback (most recent call last):
2019-06-11 10:05:42   File "C:/Users/xxx/Desktop/252/Python/ChunksPS2.py", line 152, in <lambda>
2019-06-11 10:05:42     proc_split = lambda: self.splitChunks()
2019-06-11 10:05:42   File "C:/Users/xxx/Desktop/252/Python/ChunksPS2.py", line 290, in splitChunks
2019-06-11 10:05:42     if new_chunk.depth_maps.meta['depth/depth_downscale']:
2019-06-11 10:05:42 AttributeError: 'NoneType' object has no attribute 'meta'

**Comment by pdxvr** [comment]
Sorry if you've been getting emails for my posts, but I kept posting the wrong log

```
2019-06-11 10:19:52 Script started...
2019-06-11 10:19:52 DuplicateChunk: items = ()
2019-06-11 10:19:52 Duplicating chunk...
2019-06-11 10:19:53 Finished processing in 0.665 sec (exit code 1)
2019-06-11 10:19:53 SaveProject
2019-06-11 10:19:53 Saving project...
2019-06-11 10:19:54 saved project in 0.172 sec
2019-06-11 10:19:54 Finished processing in 0.172 sec (exit code 1)
2019-06-11 10:19:54 Traceback (most recent call last):
2019-06-11 10:19:54   File "C:/Users/xx/Desktop/252/Python/ChunksPS.py", line 152, in <lambda>
2019-06-11 10:19:54     proc_split = lambda: self.splitChunks()
2019-06-11 10:19:54   File "C:/Users/xx/Desktop/252/Python/ChunksPS.py", line 291, in splitChunks
2019-06-11 10:19:54     new_chunk.buildDepthMaps(quality=quality,
2019-06-11 10:19:54 AttributeError: 'PhotoScan.Chunk' object has no attribute 'buildDepthMaps'
```

**Comment by PolarNick239** [comment]
Method ```buildDepthMaps``` was added in version 1.4.0 build 5532. Can you please tell what PhotoScan version and build number are you using? (you can see version and build number in console on PhotoScan launch or via Help -> About)

**Comment by pdxvr** [comment]
It's on our school computers and the term is nearly over so I may not get back there to check the version. It's in the 1.4 range though

**Comment by PolarNick239** [comment]
It is most likely just an older version (older than 1.4.0 build 5532).
Please feel free to re-open the issue if you encounter the problem again.
