### ISSUE TITLE
Updating script written for 1.5.0 for new version

### ISSUE THREAD

**Issue by henrypearce4D** [agisoft-llc/metashape-scripts#77]
I have a script that worked for an older version but doesn't on new versions. Is there a simple way to update it to work or are the changes to the python api to much?

[PS150_align_by_good_cameras.zip](https://github.com/agisoft-llc/metashape-scripts/files/14101715/PS150_align_by_good_cameras.zip)

**Comment by Jordan-Pierce** [comment]
What's the error that you're receiving?  It's a big jump from 1.5 to 2.1 so there's definitely some updates that need to be made, but looking at your script, maybe not that much.

**Comment by henrypearce4D** [comment]
Well it starts with this;
`2024-01-31 14:16:42 Error: name 'doc' is not defined`

**Comment by alexey-pasumansky** [comment]
Hello Henry,

In my version of the same script I have the following two lines added to the beginning of  __init__ and proc_all functions:
```
		global doc
		doc = Metashape.app.document
```

**Comment by henrypearce4D** [comment]
Hi Alexey thanks for the advice, I added what you listed the pop-up window now appears.
When running I get this message;

```
2024-01-31 14:56:19 Traceback (most recent call last):
2024-01-31 14:56:19   File "C:/Users/admin/AppData/Local/Agisoft/Metashape Pro/scripts/PS150_align_by_good_cameras_mod.py", line 75, in <lambda>
2024-01-31 14:56:19     proc_chunks = lambda : self.proc_all()
2024-01-31 14:56:19   File "C:/Users/admin/AppData/Local/Agisoft/Metashape Pro/scripts/PS150_align_by_good_cameras_mod.py", line 154, in proc_all
2024-01-31 14:56:19     self.check_cams(chunk)
2024-01-31 14:56:19   File "C:/Users/admin/AppData/Local/Agisoft/Metashape Pro/scripts/PS150_align_by_good_cameras_mod.py", line 88, in check_cams
2024-01-31 14:56:19     point_proj = point_cloud.projections
2024-01-31 14:56:19 AttributeError: 'NoneType' object has no attribute 'projections'
```

I tested removing the line 88

`		point_proj = point_cloud.projections`

And the other chunks photos all get disabled and I get the message;

```
2024-01-31 15:01:02 Script started...
2024-01-31 15:01:02 Chunk 'Frame000001' is reference. Skipping...
2024-01-31 15:01:02 Cameras in 'Frame000002' checked.
2024-01-31 15:01:02 Cameras in 'Frame000003' checked.
2024-01-31 15:01:02 Cameras in 'Frame000004' checked.
2024-01-31 15:01:02 Traceback (most recent call last):
2024-01-31 15:01:02   File "C:/Users/admin/AppData/Local/Agisoft/Metashape Pro/scripts/PS150_align_by_good_cameras_mod.py", line 75, in <lambda>
2024-01-31 15:01:02     proc_chunks = lambda : self.proc_all()
2024-01-31 15:01:02   File "C:/Users/admin/AppData/Local/Agisoft/Metashape Pro/scripts/PS150_align_by_good_cameras_mod.py", line 163, in proc_all
2024-01-31 15:01:02     doc.alignChunks(list_chunks, reference, "cameras")
2024-01-31 15:01:02 TypeError: invalid value type
```

**Comment by alexey-pasumansky** [comment]
Hello Henry,

I have updated the script a bit to fit 2.1 version API. It should work if all chunks used for alignment have tie points.

Will check, how to fix the 'NoneType' object has no attribute 'projections' in order to ignore chunks with no Tie Points.

**Comment by henrypearce4D** [comment]
Its working fantastic!

That tie point issue was weird because all chunks do have tie points

Thanks so much guys!
