### ISSUE TITLE
export to Gaussian: no .bin files

### ISSUE THREAD

**Issue by cyrilpreiss** [agisoft-llc/metashape-scripts#81]
Hi, i'm trying to use the export to gaussian script but the sparse/0 folder is always empty.

any idea ?

**Comment by PolarNick239** [comment]
Hi, can you please share log of script processing (you see it in Console)?

If you can provide dataset (or part of it) that reproduces the problem - please send it to us at [support@agisoft.com](mailto:support@agisoft.com) with link to this issue. So we will be able to reproduce and analyze the problem.

**Comment by cyrilpreiss** [comment]
hi, thanks for the quick reply, hee is the log:

2024-03-05 10:08:22 All chunks: False
2024-03-05 10:08:22 All frames: True
2024-03-05 10:08:22 Zero cx and cy: True
2024-03-05 10:08:22 Use local coordinate frame: False
2024-03-05 10:08:22 Image quality: 90
2024-03-05 10:08:22 Export images: True
2024-03-05 10:08:22 Confirm deletion: True
2024-03-05 10:08:22 Using pinhole model instead of simple_pinhole: True
2024-03-05 10:08:22 Using only uncropped projections: True
2024-03-05 10:08:33 E:/work in progress/ritz sdb/splat3/
2024-03-05 10:08:33 
2024-03-05 10:08:33 E:/work in progress/ritz sdb/splat3/Chunk 1/
2024-03-05 10:08:33 Calibrations:
2024-03-05 10:08:33 0 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 1 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 2 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 3 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 4 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 5 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 6 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 7 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 8 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 9 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 10 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 11 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 12 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 13 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 14 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 15 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 16 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 17 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 18 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 19 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 20 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 21 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 22 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 23 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 24 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 25 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 26 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 27 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 28 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 29 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 30 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 31 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 32 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 33 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 34 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 35 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 36 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 37 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 38 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 39 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 40 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 41 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 42 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 43 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 44 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 45 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 46 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 47 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 48 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 49 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 50 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 51 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 52 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 53 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 54 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 55 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 56 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 57 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 58 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 59 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 60 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 61 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 62 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 63 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 64 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 65 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:33 66 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 67 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 68 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 69 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 70 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 71 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 72 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 73 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 74 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 75 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 76 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 77 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 78 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 79 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 80 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 81 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 82 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 83 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 84 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 85 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 86 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 87 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 88 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 89 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 90 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 91 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 92 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 93 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 94 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 95 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 96 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 97 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 98 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 99 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 100 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 101 2559.4999202100166 5118 5118 -0.0 -0.0
2024-03-05 10:08:34 102 3801.3258282610486 6240 9342 -0.0 -0.0
2024-03-05 10:08:34 103 3810.547156743115 9308 6220 -0.0 -0.0
2024-03-05 10:08:40 Found 9142 cropped projections
2024-03-05 10:22:38 Traceback (most recent call last):
2024-03-05 10:22:38   File "E:/work in progress/export_for_gaussian_splatting.py", line 682, in <lambda>
2024-03-05 10:22:38     proc = lambda : self.run_export()
2024-03-05 10:22:38   File "E:/work in progress/export_for_gaussian_splatting.py", line 547, in run_export
2024-03-05 10:22:38     export_for_gaussian_splatting(params, self.pBar)
2024-03-05 10:22:38   File "E:/work in progress/export_for_gaussian_splatting.py", line 503, in export_for_gaussian_splatting
2024-03-05 10:22:38     save_undistorted_images(params, frame, folder, calibs)
2024-03-05 10:22:38   File "E:/work in progress/export_for_gaussian_splatting.py", line 333, in save_undistorted_images
2024-03-05 10:22:38     img.save(folder + name)
2024-03-05 10:22:38 RuntimeError: Unknown image format

**Comment by cyrilpreiss** [comment]
i have tried the export with only 10 images enabled and i get the same error.
images are in jpg

**Comment by Teran72** [comment]
Hi!
Do you have anything camera-alike in your project, like camera track?

**Comment by Teran72** [comment]
And can you, please, share a path and a name of one of the images?
Maybe, names of the images contain dots?

**Comment by cyrilpreiss** [comment]
no camera track but i have laserscans.
here is one of the photo names: 240129-104621-DSC04283_DxO7.jpg

**Comment by cyrilpreiss** [comment]
disabling the laser scans fixed the issue !
